// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJHQdn9ZNYy2bGdejiaDIZMfb423LByHw',
    appId: '1:624970116706:web:ff57ef467f76b096672b3b',
    messagingSenderId: '624970116706',
    projectId: 'scholar-chat-ahmed26',
    authDomain: 'scholar-chat-ahmed26.firebaseapp.com',
    storageBucket: 'scholar-chat-ahmed26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByk0lqczNvvFzlS9pOHvkBLUMwrjT87Hw',
    appId: '1:624970116706:android:f3a83f9bf7dde223672b3b',
    messagingSenderId: '624970116706',
    projectId: 'scholar-chat-ahmed26',
    storageBucket: 'scholar-chat-ahmed26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTmy8R291Zx_8_ATq6tPYwsEM__TkDazk',
    appId: '1:624970116706:ios:62512e683c7e983b672b3b',
    messagingSenderId: '624970116706',
    projectId: 'scholar-chat-ahmed26',
    storageBucket: 'scholar-chat-ahmed26.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTmy8R291Zx_8_ATq6tPYwsEM__TkDazk',
    appId: '1:624970116706:ios:62512e683c7e983b672b3b',
    messagingSenderId: '624970116706',
    projectId: 'scholar-chat-ahmed26',
    storageBucket: 'scholar-chat-ahmed26.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJHQdn9ZNYy2bGdejiaDIZMfb423LByHw',
    appId: '1:624970116706:web:1e005529f40b7a4a672b3b',
    messagingSenderId: '624970116706',
    projectId: 'scholar-chat-ahmed26',
    authDomain: 'scholar-chat-ahmed26.firebaseapp.com',
    storageBucket: 'scholar-chat-ahmed26.firebasestorage.app',
  );
}
